# Generated by Django 2.1.2 on 2018-10-25 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import test_assignment.apps.account.managers


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', test_assignment.apps.account.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
