# Generated by Django 2.1.2 on 2018-10-25 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181025_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
